apiVersion: v2
name: security-kyverno-policies
description: This helm chart contains a set of Kyverno policies to secure a Kubernetes cluster.
version: 0.1.1
appVersion: "1.0.1"
engine: gotpl
sources: ["https://github.com/rcarpio-hbo/security-kyverno-policies/tree/main/security-policies"]